apiVersion: v1
kind: Service
metadata:
  name: endpoints-service
spec:
  ports:
    - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: endpoints-service
subsets:
  - addresses:
      - ip: 10.244.0.12
      - ip: 10.244.0.17
    ports:
      - port: 8000
