apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-2
  labels:
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: bokovets/kuber
      ports:
        - containerPort: 8080
